export const planesData = [
  {
    id: "boeing-747",
    title: "Boeing 747 - The Queen of the Skies",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/British_Airways_G-BNLU-2008-09-13-YVR.jpg/1200px-British_Airways_G-BNLU-2008-09-13-YVR.jpg",
    description:
      "The Boeing 747, often referred to as the 'Queen of the Skies', revolutionized air travel with its iconic hump and impressive size. It was the first wide-body commercial airliner and remained the largest passenger aircraft for decades until the Airbus A380.",
    specs: [
      "Length: 231 feet 10 inches (70.66 m)",
      "Wingspan: 196 feet 5 inches (59.9 m)",
      "Cruising speed: 570 mph (920 km/h)",
      "Maximum capacity: Up to 660 passengers",
      "Range: Up to 8,000 nautical miles (14,815 km)",
    ],
    history:
      "The Boeing 747 made its first commercial flight in 1970 with Pan American World Airways. It was designed in the late 1960s as a response to the growing demand for air travel. The distinctive hump at the front of the aircraft houses the cockpit and upper deck, which was originally designed to allow the aircraft to be converted to a cargo plane as it was believed that supersonic aircraft would eventually replace it for passenger service.",
    funFacts: [
      "The 747 has enough fuel capacity to power a small car for 20 years",
      "The Wright Brothers' first flight could have been performed within the 747's economy class cabin",
      "Over 1,500 Boeing 747s have been built since its introduction",
      "The 747 has traveled more than 35 billion nautical miles, equivalent to 65,000 trips to the moon and back",
    ],
    known: false,
  },
  {
    id: "concorde",
    title: "Concorde - Breaking the Sound Barrier",
    image:
      "https://www.heraldnet.com/wp-content/uploads/2019/03/15799149_web1_M-Concorde-EDH-190305.jpg",
    description:
      "The Concorde was a British-French turbojet-powered supersonic passenger airliner that operated from 1976 to 2003. It had a maximum speed of twice the speed of sound (Mach 2.04) and could cross the Atlantic in just under 3.5 hours.",
    specs: [
      "Length: 202 feet 4 inches (61.66 m)",
      "Wingspan: 83 feet 10 inches (25.6 m)",
      "Cruising speed: Mach 2.04 (1,354 mph/2,180 km/h)",
      "Maximum capacity: 100-128 passengers",
      "Range: 4,500 miles (7,250 km)",
    ],
    history:
      "Concorde was jointly developed by the United Kingdom and France in the 1960s. The aircraft made its first commercial flight in 1976 and continued service until 2003. Only 20 Concordes were ever built, and they were primarily operated by British Airways and Air France. The aircraft's retirement was due to a combination of factors, including the crash of Air France Flight 4590 in 2000, declining passenger numbers following the September 11 attacks, and increasing maintenance costs.",
    funFacts: [
      "Due to the heat generated by supersonic flight, the Concorde would expand by up to 10 inches (25 cm) during flight",
      "The Concorde's drooping nose was designed to improve pilot visibility during takeoff and landing",
      "Passengers could see the curvature of the Earth from Concorde's cruising altitude of 60,000 feet",
      "The sonic boom created by Concorde was so loud that the aircraft was prohibited from flying at supersonic speeds over land",
    ],
    known: false,
  },
  {
    id: "sr-71-blackbird",
    title: "SR-71 Blackbird - The Fastest Air-Breathing Manned Aircraft",
    image:
      "https://assets.newatlas.com/dims4/default/fab6035/2147483647/strip/true/crop/889x500+23+0/resize/1200x675!/quality/90/?url=http%3A%2F%2Fnewatlas-brightspot.s3.amazonaws.com%2Farchive%2Fblackbird-plane-8.jpg",
    description:
      "The Lockheed SR-71 Blackbird is a long-range, high-altitude, Mach 3+ strategic reconnaissance aircraft developed by Lockheed's Skunk Works division. It remains the fastest air-breathing manned aircraft in the world.",
    specs: [
      "Length: 107 feet 5 inches (32.74 m)",
      "Wingspan: 55 feet 7 inches (16.94 m)",
      "Maximum speed: Mach 3.3+ (2,200+ mph/3,540+ km/h)",
      "Crew: 2 (Pilot and Reconnaissance Systems Officer)",
      "Range: 2,900 nautical miles (5,400 km)",
    ],
    history:
      "The SR-71 was designed in the 1960s to replace the U-2 spy plane. It flew from 1964 to 1998 and was used primarily by the United States Air Force and NASA. The aircraft was designed to outfly missiles rather than evade them, and no SR-71 was ever shot down despite over 4,000 missiles being fired at them during their operational history.",
    funFacts: [
      "The SR-71's titanium body would expand so much due to air friction heat that the aircraft would leak fuel while on the ground",
      "The pilots had to wear pressurized suits similar to those worn by astronauts",
      "The SR-71 could outrun surface-to-air missiles fired at it",
      "The aircraft's engines actually worked more efficiently at higher speeds",
    ],
    known: false,
  },
  {
    id: "wright-flyer",
    title: "Wright Flyer - The First Successful Airplane",
    image:
      "https://www.wright-brothers.org/Information_Desk/Just_the_Facts/Airplanes/Wright_Airplane_images/1904_Flyer_II/1904_Flyer_Flight_16Nov.jpg",
    description:
      "The Wright Flyer (also known as Flyer I or 1903 Flyer) was the first successful heavier-than-air powered aircraft. It was designed and built by the Wright brothers, and they flew it four times on December 17, 1903, near Kill Devil Hills, North Carolina.",
    specs: [
      "Length: 21 feet 1 inch (6.43 m)",
      "Wingspan: 40 feet 4 inches (12.3 m)",
      "Engine: 12 horsepower (8.9 kW) custom-built",
      "Weight: 605 pounds (274 kg)",
      "Maximum speed: 30 mph (48 km/h)",
    ],
    history:
      "After years of research and experimentation with gliders, the Wright brothers built the Flyer in 1903. On December 17, 1903, Orville Wright made the first flight, which lasted 12 seconds and covered 120 feet. The fourth and final flight of the day, piloted by Wilbur, covered 852 feet in 59 seconds. These flights marked the beginning of the era of powered flight.",
    funFacts: [
      "The Wright brothers built their own wind tunnel to test wing designs",
      "The first flight was shorter than the wingspan of a modern Boeing 747",
      "The Wright brothers won a coin toss to decide who would pilot the first flight",
      "The original Wright Flyer is now displayed at the National Air and Space Museum in Washington, D.C.",
    ],
    known: false,
  },
  {
    id: "spitfire",
    title: "Supermarine Spitfire - Icon of the Battle of Britain",
    image:
      "https://www.airforce.gov.au/sites/default/files/2022-12/20200914raaf8622332_04.jpg",
    description:
      "The Supermarine Spitfire is a British single-seat fighter aircraft that was used by the Royal Air Force and other Allied countries during and after World War II. It was produced in greater numbers than any other British aircraft and was the only British fighter to be in continuous production throughout the war.",
    specs: [
      "Length: 29 feet 11 inches (9.12 m)",
      "Wingspan: 36 feet 10 inches (11.23 m)",
      "Maximum speed: 378 mph (608 km/h)",
      "Armament: Eight .303 Browning machine guns",
      "Range: 479 miles (771 km)",
    ],
    history:
      "The Spitfire was designed by R. J. Mitchell and first flew in 1936. It became famous during the Battle of Britain in 1940, where it played a crucial role in defeating the Luftwaffe and preventing a German invasion of Britain. The Spitfire's elliptical wing design gave it excellent maneuverability and a higher top speed than many of its contemporaries.",
    funFacts: [
      "The Spitfire's name was suggested by Sir Robert McLean, chairman of Vickers Aviation, who called his daughter 'a little spitfire'",
      "Over 20,000 Spitfires were built in 24 different variants",
      "The distinctive elliptical wing design was chosen for aerodynamic efficiency, not aesthetics",
      "The Spitfire could climb at a rate of 2,600 feet per minute",
    ],
    known: false,
  },
  {
    id: "lockheed-constellation",
    title: "Lockheed Constellation - The Aircraft That Saved Lockheed",
    image:
      "https://static1.simpleflyingimages.com/wordpress/wp-content/uploads/2024/02/shutterstock_1598603224-1.jpeg",
    description:
      "The Lockheed Constellation ('Connie') was a propeller-driven, four-engine airliner built by Lockheed Corporation between 1943 and 1958. It was known for its distinctive triple-tail design and dolphin-shaped fuselage. The Constellation was used as a civilian airliner and as a military and civilian air transport.",
    specs: [
      "Length: 116 feet 2 inches (35.41 m)",
      "Wingspan: 123 feet (37.49 m)",
      "Cruising speed: 340 mph (547 km/h)",
      "Capacity: Up to 109 passengers",
      "Range: 5,400 miles (8,700 km)",
    ],
    history:
      "The Constellation was developed at the request of Howard Hughes for Transcontinental and Western Air (TWA). It first flew in 1943 and entered commercial service in 1945. The aircraft was revolutionary for its time, featuring a pressurized cabin, hydraulic-boosted controls, and de-icing equipment. The Constellation set numerous records and was one of the most elegant and efficient aircraft of its era.",
    funFacts: [
      "Howard Hughes personally piloted the first Constellation prototype from California to Washington, D.C., setting a transcontinental speed record",
      "The Constellation's pressurized cabin allowed it to fly above most weather disturbances",
      "The aircraft's distinctive triple-tail design was necessary to keep the aircraft's height low enough to fit in existing hangars",
      "The last commercial passenger flight of a Constellation was in 1967, but the aircraft continued to be used for cargo operations into the 1980s",
    ],
    known: false,
  },
];
